import {
  SiReact,
  SiNextdotjs,
  SiPrisma,
  SiDocker,
  SiAmazonwebservices,
  SiCloudflare,
  SiServerless,
  SiVim,
  SiVisualstudiocode,
  SiExpress,
  SiPython,
  SiFastapi,
  SiMysql,
  SiPostgresql,
  SiOpenai,
  SiFigma,
  SiLinux,
  SiTypescript,
  SiJavascript,
  SiGit,
  SiTailwindcss,
  SiC,
  SiCplusplus,
  SiNeovim,
  SiHtml5,
  SiCss3,
  SiJquery,
  SiRedux,
  SiGraphql,
  SiSass,
  SiDjango,
  SiFlask,
  SiGo,
  SiRust,
  SiKubernetes,
  SiTerraform,
  SiAnsible,
  SiJenkins,
  SiMongodb,
  SiFirebase,
  SiRedis,
  SiNginx,
  SiWebpack,
  SiBabel,
  SiKibana,
  SiElastic,
  SiCircleci,
  SiDigitalocean,
  SiHeroku,
  SiMicrosoftazure,
  SiGitlab,
  SiNpm,
  SiYarn,
  SiBootstrap,
  SiStyledcomponents,
  SiChakraui,
  SiFlutter,
  SiElectron,
  SiReduxsaga,
  SiNumpy,
  SiPandas,
  SiOpencv,
  SiTensorflow,
  SiPytorch,
  SiTableau,
  SiOracle,
  SiSnowflake,
  SiWordpress,
  SiMagento,
  SiJoomla,
  SiLaravel,
  SiSpring,
  SiDotnet,
  SiXamarin,
  SiUnity,
  SiUnrealengine,
  SiRaspberrypi,
  SiArduino,
  SiHomeassistant,
  SiJetbrains,
  SiPhp,
  SiScala,
  SiHaskell,
  SiLatex,
  SiInkscape,
  SiGimp,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiKotlin,
  SiSwift,
  SiR,
  SiJulia,
  SiCloudera,
  SiPowerbi,
} from "react-icons/si";
const icons = [
  { component: SiReact, color: "#61DAFB" },
  { component: SiNextdotjs, color: "black" },
  { component: SiPrisma, color: "#2D3748" },
  { component: SiDocker, color: "#2496ED" },
  { component: SiAmazonwebservices, color: "#FF9900" },
  { component: SiCloudflare, color: "#F38020" },
  { component: SiServerless, color: "#FD5750" },
  { component: SiVim, color: "#019733" },
  { component: SiVisualstudiocode, color: "#007ACC" },
  { component: SiExpress, color: "black" },
  { component: SiPython, color: "#3776AB" },
  { component: SiFastapi, color: "#05998B" },
  { component: SiMysql, color: "#4479A1" },
  { component: SiPostgresql, color: "#336791" },
  { component: SiOpenai, color: "#412991" },
  { component: SiFigma, color: "#F24E1E" },
  { component: SiLinux, color: "yellow" },
  { component: SiTypescript, color: "#2496ED" },
  { component: SiJavascript, color: "yellow" },
  { component: SiGit, color: "maroon" },
  { component: SiTailwindcss, color: "skyblue" },
  { component: SiC, color: "gray" },
  { component: SiCplusplus, color: "lightblue" },
  { component: SiNeovim, color: "#57A143" },
  { component: SiHtml5, color: "#E34F26" },
  { component: SiCss3, color: "#1572B6" },
  { component: SiJquery, color: "#0769AD" },
  { component: SiRedux, color: "#764ABC" },
  { component: SiGraphql, color: "#E10098" },

  // { component: SiSass, color: "#CC6699" },
  // { component: SiDjango, color: "#092E20" },
  // { component: SiFlask, color: "black" },
  // { component: SiGo, color: "#00ADD8" },
  // { component: SiRust, color: "#DEA584" },
  // { component: SiKubernetes, color: "#326CE5" },
  // { component: SiTerraform, color: "#623CE4" },
  // { component: SiAnsible, color: "#EE0000" },
  // { component: SiJenkins, color: "#D24939" },
  // { component: SiMongodb, color: "#47A248" },
  // { component: SiFirebase, color: "#FFCA28" },
  // { component: SiRedis, color: "#DC382D" },
  // { component: SiNginx, color: "#009639" },
  // { component: SiWebpack, color: "#8DD6F9" },
  // { component: SiBabel, color: "#F9DC3E" },
  // { component: SiWebpack, color: "#8DD6F9" },
  // { component: SiKibana, color: "#005571" },
  // { component: SiElastic, color: "#005571" },
  // { component: SiCircleci, color: "#343434" },
  // { component: SiFirebase, color: "#FFCA28" },
  // { component: SiDigitalocean, color: "#0080FF" },
  // { component: SiHeroku, color: "#430098" },
  // { component: SiMicrosoftazure, color: "#0078D4" },
  // { component: SiGitlab, color: "#FCA121" },
  // { component: SiNpm, color: "#CB3837" },
  // { component: SiYarn, color: "#2C8EBB" },
  // { component: SiBootstrap, color: "#7952B3" },

  // { component: SiStyledcomponents, color: "#DB7093" },
  // { component: SiChakraui, color: "#319795" },
  // { component: SiFlutter, color: "#02569B" },
  // { component: SiElectron, color: "#47848F" },
  // { component: SiWebpack, color: "#8DD6F9" },
  // { component: SiReduxsaga, color: "#999999" },
  // { component: SiRedux, color: "#764ABC" },
  // { component: SiNumpy, color: "#013243" },
  // { component: SiPandas, color: "#150458" },
  // { component: SiOpencv, color: "#5C3EE8" },
  // { component: SiTensorflow, color: "#FF6F00" },
  // { component: SiPytorch, color: "#EE4C2C" },
  // { component: SiTableau, color: "#E97627" },
  // { component: SiOracle, color: "#F80000" },
  // { component: SiSnowflake, color: "#56B9EB" },

  // { component: SiWordpress, color: "#21759B" },
  // { component: SiMagento, color: "#EE672F" },
  // { component: SiJoomla, color: "#F44321" },
  // { component: SiLaravel, color: "#FF2D20" },
  // { component: SiSpring, color: "#6DB33F" },
  // { component: SiDotnet, color: "#5C2D91" },
  // { component: SiXamarin, color: "#3498DB" },
  // { component: SiUnity, color: "#222C37" },
  // { component: SiUnrealengine, color: "#0E1128" },
  // { component: SiTensorflow, color: "#FF6F00" },
  // { component: SiRaspberrypi, color: "#C51A4A" },
  // { component: SiArduino, color: "#00979D" },
  // { component: SiHomeassistant, color: "#41BDF5" },
  // { component: SiNginx, color: "#009639" },
  // { component: SiJetbrains, color: "#000000" },
  // { component: SiPhp, color: "#777BB4" },
  // { component: SiScala, color: "#DC322F" },
  // { component: SiHaskell, color: "#5D4F85" },
  // { component: SiLatex, color: "#008080" },
  // { component: SiInkscape, color: "#000000" },
  // { component: SiGimp, color: "#5C5543" },
  // { component: SiAdobephotoshop, color: "#31A8FF" },
  // { component: SiAdobeillustrator, color: "#FF9A00" },
  // { component: SiKotlin, color: "#0095D5" },
  // { component: SiSwift, color: "#FA7343" },
  // { component: SiR, color: "#276DC3" },
  // { component: SiJulia, color: "#9558B2" },
  // { component: SiCloudera, color: "#F88900" },
  // { component: SiPowerbi, color: "#F2C811" },
];

export default icons;
